### ISSUE TITLE
Add more package managers to libusb check

### ISSUE THREAD

**Issue by moriczgergo** [moriczgergo/fusee-legere#1]
In fusée légère, we have checks to make sure libusb is installed. ~~I could only add dpkg support, since that's what I'm familiar with ([code](https://github.com/moriczgergo/fusee-legere/blob/02486d17f041d48e8538791603cf37abe83e7476/fusee-legere.sh#L85-L94)).~~

~~FL's libusb check has/needs multiple versions by package manager, not by distro (see the if statement in the code above). We'd recommend **not** to grep the result of the check, but to implement an if statement based on the exit code, if possible.~~

~~Currently supported package managers: (list will be updated with future changes/PRs)~~
 * ~~dpkg (a299c00)~~

*EDIT:* Recommended by @Qyriad (and others on the ReSwitched Discord), we can use `ldconfig -p` and `grep` to detect the presence of `/lib/libusb-1.0.so`. I have impelemented that method, and it is under testing on the ldconfig branch.

If you would like to help, ~~open a PR!~~ test the ldconfig branch on a distro yourself. Thanks.

**Comment by Qyriad** [comment]
Might be *much* easier to check for the presence of `/lib/libusb-1.0.so`

**Comment by moriczgergo** [comment]
@Qyriad good point! I’ll check the location for sure on multiple devices though before attempting to do that.

**Comment by moriczgergo** [comment]
This method is currently in testing, see branch ldconfig.
